---
-hosts: localhost
 tasks:

  -name: install httpd server
   yum: name=httpd state=latest

  -name: edit httpd.conf
   replace:
    path: /etc/httpd/httpd.conf
    regexp: 'denied'
    replace: 'granted'
    after: '<Directory\s/>'
    before: '</Directory>'
    backup: yes
  -name: copy index.html
   copy:
    src: ~/index.html
    dest: /var/www/html/index.html

  -name: restart httpd server
   service: name=httpd state=restarted
